### PR TITLE
TAMAYA-277: LHF: use try-with-resources with BufferedReader

### PR DESCRIPTION
**Pull request by acoburn**
This opens a `BufferedReader` in a try-with-resources block to ensure that the resource is properly closed in the event of an exception.

### CODE REVIEW

**Comment by acoburn** [comment]
@ottlinger the best way to test OSGi is with Pax-Exam, but that adds a huge amount of complexity and should probably be part of a separate effort. In the meantime, though, I can definitely add some simple tests.

**Comment by ottlinger** [comment]
... or we merge the changes although they break the quality build:
https://sonarcloud.io/project/issues?id=apache_incubator-tamaya&pullRequest=49&resolved=false

Do you see a chance to reduce the duplicate-warning? I tried to extract the stuff into a method, but that only made things worse.

**Comment by acoburn** [comment]
I suppose the question is whether Sonar non-compliance should be allowed to fail a build or not. I personally find Sonar to be very useful, but I typically put it in a `after_success` clause like this:

```
script: mvn clean install 
after_success: mvn sonar:sonar -Dsonar.organization=apache -Dsonar.projectKey=apache_incubator-tamaya
```

**Comment by acoburn** [comment]
@ottlinger all the checks now pass.

**Comment by ottlinger** [comment]
@acoburn thanks - my IDE marked the first lines in
* processEntryPath(Bundle bundle, String entryPath)
* removeEntryPath(Bundle bundle, String entryPath)
as possible duplicates. Your solution is much simpler and does not break the quality build.

Thanks :+1:

**Pull request merged**
