### PR TITLE
WIP: TAMAYA-386: Fix project setup/enable example project

### PR DESCRIPTION
**Pull request by ottlinger**
After upgrading VertX we realized that the project is not properly build at the moment, thus:
reintegrate and adapt to new API.

### CODE REVIEW

**Comment by ottlinger** [comment]
Current WorkInProgress-state:
* (/) no maven warnings
* build failures:

```

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project tamaya-example-distributed: 
Could not resolve dependencies for project org.apache.tamaya.examples:tamaya-example-distributed:jar:0.4-incubating-SNAPSHOT: 


The following artifacts could not be resolved: org.apache.tamaya:tamaya-core:jar:0.3-incubating-SNAPSHOT, 


org.apache.tamaya.ext:tamaya-injection-api:jar:0.3-incubating-SNAPSHOT, org.apache.tamaya.ext:tamaya-injection:jar:0.3-incubating-SNAPSHOT, 
org.apache.tamaya.ext:tamaya-mutable-config:jar:0.3-incubating-SNAPSHOT, org.apache.tamaya:tamaya-api:jar:0.3-incubating-SNAPSHOT, 
org.apache.tamaya.ext:tamaya-functions:jar:0.3-incubating-SNAPSHOT, 
org.apache.tamaya.ext:tamaya-spisupport:jar:0.3-incubating-SNAPSHOT: 


Could not find artifact org.apache.tamaya:tamaya-core:jar:0.3-incubating-SNAPSHOT in apache.snapshots (https://repository.apache.org/snapshots) -> [Help 1]


https://github.com/apache/incubator-tamaya/pull/46
```

**Comment by acoburn** [comment]
I think we should consider moving this example project to the `tamaya-extensions` repository. This particular example depends on `org.apache.tamaya.ext/tamaya-injection-api` (among others). Even if those dependencies are addressed, imagine what would happen during a release (e.g. 0.4.0): one would first need to `mvn install -pl '!:tamaya-example-distributed'` on the core repository, then `mvn install` on the extensions repository and only _then_ can one run `mvn verify` (i.e. with this example) on the core repository.

Moving this to `tamaya-extensions` would eliminate the circular dependency.

**Comment by ottlinger** [comment]
@acoburn I'm in favour of your proposal .... and remember a discussion to create a new repo tamaya-examples .... but moving it into extensions to get rid of the circular deps makes sense to me.

**Comment by peculater** [comment]
I believe that after merging the two PRs above (https://github.com/apache/incubator-tamaya-extensions/pull/38 and https://github.com/apache/incubator-tamaya/pull/55) this PR can be closed.

**Comment by ottlinger** [comment]
Thanks @peculater - can you close the TAMAYA-386 in jira as well.

**Pull request merged**
