### PR TITLE
Replace Jackson with Apache Johnzon

### PR DESCRIPTION
**Pull request by salyh**
- Replace Jackson with Apache Johnzon
- Typos

### CODE REVIEW

**Comment by johnament** [comment]
Any chance we can do this in a way that the old jackson provider remains, and a new Johnzon provider is added?  It looks like the johnzon dependency should be test scoped since all of the relevant tamaya code is based on javax.json.

**Comment by salyh** [comment]
javax.json.* is only the API (JSR 353) without implementation. So Johnzon (which is the implementation) have to be also in the runtime classpath. Jackson does not implement javax.json JSR 353 API.

**Comment by atsticks** [comment]
I will look at the patch later here, and if it looks good (what I assume) I
will update the repo. In general using the standardized API makes for me
more sense then relying on a third party API, especially also for later use
as part of any kind of container that already provides the required API and
impl as part of the container infrastructure ;)

Best,
Anatole

2015-08-16 15:15 GMT+02:00 Hendrik Saly <notifications@github.com>:

> javax.json.* is only the API (JSR 353) without implementation. So Johnzon
> (which is the implementation) have to be also in the runtime classpath.
> Jackson does not implement javax.json JSR 353 API.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-tamaya/pull/6#issuecomment-131549076>
> .
>



-- 
*Anatole Tresch*
Java Engineer & Architect, JSR Spec Lead
Glärnischweg 10
CH - 8620 Wetzikon

*Switzerland, Europe Zurich, GMT+1*
*Twitter:  @atsticks*
*Blogs: **http://javaremarkables.blogspot.ch/
<http://javaremarkables.blogspot.ch/>*

*Google: atsticksMobile  +41-76 344 62 79*

**Comment by ottlinger** [comment]
@salyh can you be so kind to close the patch as it already seems to be applied (we didn't have a good github integration at the time of creation) - thanks for your help

**Comment by atsticks** [comment]
Already done.

**Pull request closed without merging**
