### PR TITLE
Add javax.annotation as import-package

### PR DESCRIPTION
**Pull request by alexsuter**

### CODE REVIEW

**Comment by ottlinger** [comment]
Thanks for the PR - could you provide a little more context? What does adding the annotation-package fix or improve? Thanks

**Comment by alexsuter** [comment]
This is needed for OSGi environement. The following exception occurs:

```
!ENTRY org.apache.tamaya.core 4 0 2018-06-28 11:25:37.890
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Exception in org.apache.tamaya.core.OSGIActivator.start() of bundle org.apache.tamaya.core.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:800)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1634)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1614)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1585)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1528)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/Priority
	at org.apache.tamaya.spisupport.PriorityServiceComparator.getPriority(PriorityServiceComparator.java:78)
	at org.apache.tamaya.spisupport.PriorityServiceComparator.getPriority(PriorityServiceComparator.java:65)
	at org.apache.tamaya.spisupport.PropertyConverterManager$1.compare(PropertyConverterManager.java:67)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at java.util.Collections.sort(Collections.java:175)
	at org.apache.tamaya.spisupport.PropertyConverterManager.register(PropertyConverterManager.java:137)
	at org.apache.tamaya.spisupport.DefaultConfigurationContext.<init>(DefaultConfigurationContext.java:78)
	at org.apache.tamaya.spisupport.DefaultConfigurationContextBuilder.build(DefaultConfigurationContextBuilder.java:409)
	at org.apache.tamaya.core.internal.CoreConfigurationBuilder.build(CoreConfigurationBuilder.java:89)
	at org.apache.tamaya.core.OSGIActivator.start(OSGIActivator.java:57)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772)
	... 12 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.Priority cannot be found by org.apache.tamaya.spisupport_0.4.0.incubating-20180628_001856-511
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 more
Root exception:
java.lang.NoClassDefFoundError: javax/annotation/Priority
	at org.apache.tamaya.spisupport.PriorityServiceComparator.getPriority(PriorityServiceComparator.java:78)
	at org.apache.tamaya.spisupport.PriorityServiceComparator.getPriority(PriorityServiceComparator.java:65)
	at org.apache.tamaya.spisupport.PropertyConverterManager$1.compare(PropertyConverterManager.java:67)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at java.util.Collections.sort(Collections.java:175)
	at org.apache.tamaya.spisupport.PropertyConverterManager.register(PropertyConverterManager.java:137)
	at org.apache.tamaya.spisupport.DefaultConfigurationContext.<init>(DefaultConfigurationContext.java:78)
	at org.apache.tamaya.spisupport.DefaultConfigurationContextBuilder.build(DefaultConfigurationContextBuilder.java:409)
	at org.apache.tamaya.core.internal.CoreConfigurationBuilder.build(CoreConfigurationBuilder.java:89)
	at org.apache.tamaya.core.OSGIActivator.start(OSGIActivator.java:57)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1634)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1614)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1585)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1528)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.lang.ClassNotFoundException: javax.annotation.Priority cannot be found by org.apache.tamaya.spisupport_0.4.0.incubating-20180628_001856-511
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 more
```

**Comment by ottlinger** [comment]
Thanks - do you have an Apache-ContributorsLicenseAgreement signed?
If so, please do not mind to file an issue in ASF's TAMAYA-Jira so that we can keep track of the changes.

Thanks for the bugfix :-)

**Comment by alexsuter** [comment]
All right! I reported the following issue: https://issues.apache.org/jira/browse/TAMAYA-343

**Comment by alexsuter** [comment]
I close this pull request. Because this has been fixed in the master branch.

**Pull request closed without merging**
